### ISSUE TITLE
Crash when loading a GIF file that isn't a GIF

### ISSUE THREAD

**Issue by gerph** [dpt/PrivateEye#9]
I got a crash when trying to load a file that had type GIF that wasn't a GIF (it was a PNG).

It looks like this is related to:

https://github.com/dpt/PrivateEye/commit/e5f5483f30c19b7347b625918d350c8d906ae670#r65563258

and

https://github.com/dpt/PrivateEye/commit/e5f5483f30c19b7347b625918d350c8d906ae670#r65563269

That is uninitialised values in the State when the file is loading.

**Comment by dpt** [comment]
Thanks. Will fix.

**Comment by dpt** [comment]
Tested locally - now fixed.
